### ISSUE TITLE
Inverse of a normalized quaternion

### ISSUE THREAD

**Issue by emilk** [bitshifter/glam-rs#131]
I am wondering if it would make sense to add this function to `Quat`:

``` rust
/// Returns the inverse of a normalized quaternion
pub fn inverse(self) -> Self {
    glam_assert!(self.is_normalized());
    self.conjugate()
}
```

Most quaternion users (including me) only has a vague understanding of the underlying mathematics, and are more interested in a higher level abstraction of using quaternions as rotors. Thus `q.conjugate()` is cryptic, while `q.inverse()` is clear. In particular, it is more obvious what `world_from_mesh.inverse()` means than `world_from_mesh.conjugate()`.

**Comment by bitshifter** [comment]
Yes I was thinking of doing that since as you say, most people look for inverse. My thinking was to offer inverse and add a function doc comment explaining that conjugate should be used instead unless you are sure your quaternion is not normalized. I don't know that I'd assert since it's not really invalid. At least if people are using inverse they can go and change them all to conjugate when they realize inverse is not necessary.

**Comment by bitshifter** [comment]
I realize now that I misread your comment (I glossed over it on my phone and thought your inverse was normalizing self before returning the conjugate). This approach does seem reasonable given most methods expect Quat to be unit length anyway.
