### ISSUE TITLE
PartialOrd gotchas

### ISSUE THREAD

**Issue by emilk** [bitshifter/glam-rs#138]
It has long been possible to write code such as `rgb.max(Vec3::ZERO).min(Vec3::ONE)` and [since Rust 1.49](https://doc.rust-lang.org/std/cmp/trait.Ord.html#method.clamp) one can also write `rgb.clamp(Vec3::ZERO, Vec3::ONE)`. This is of course a bug that most likely does not follow the intention of the author.

I would suggest these remedies:

## Remove `impl PartialOrd` from all glam types
As long as `Vec3` etc implemented `PartialOrd`, bugs like described above will be possible.

I think comparing vectors with `<` is a rare convenience, and putting `Vec3` in a `BTreeSet/Map` is probably not a good idea anyway (though it might be tempting since it is [difficult to but them in a `HashSet/Map`](https://github.com/bitshifter/glam-rs/issues/123)).

## Add `to_array()` helpers
In the rare case a user wants to order a vector they can do so pretty easily if we add a helper function:

``` rust
impl Vec3 {
    fn to_array(&self) -> [f32; 3] { … }
}
```

This will allow you to write `v0.to_array() < v1.to_array()` if you really want to order `Vec3`. It also has other nice benefits, such as allowing `let [x y, z] = v.to_array();`

## Add component-wise `min`, `max` and `clamp`

I'm unsure about the naming of these, but I think these are crucial ergonomic wins. For instance:

``` rust
let rgb = rgb.clamp_comp(Vec3::ZERO, Vec3::ONE).
let positive = vec.max_comp(Vec3::ZERO);
```

# Next steps
If this sounds good I can make a PR

**Comment by bitshifter** [comment]
I added `PartialOrd` since `[f32;3]` and `(f32,f32,f32)` supports it, but I can see that it's probably going to do unexpected things so removing it seems reasonable.

On the `to_array` front, are you aware that all types support `From` for going in and out of arrays and tuples? I just wanted to check, `to_array` could be more ergonomic and discoverable than using From so I'm assuming that's why you are suggesting it.

I am a little bit unsure what you mean by component wise `min`, `max` and clamp? Are these returning `Self``? How are they different from https://docs.rs/glam/0.12.0/glam/f32/struct.Vec3.html#method.min and https://docs.rs/glam/0.12.0/glam/f32/struct.Vec3.html#method.max? I would be fine with adding a `clamp` that works similarly the existing `min` and `max`.

**Comment by emilk** [comment]
Oh, I had missed `min` and `max`. I guess we don't need different naming of them, nor for `clamp`.

**Comment by bitshifter** [comment]
Re-reading this, glam vectors have `min` and `max` methods, these are the ones that will be used. It is the `Ord` trait that has `min`, `max` and `clamp` methods so these won't be defined for glam types.

```
fn test_clamp() {
    let v = Vec3::new(-2.0, 2.0, -3.0);
    let v = v.clamp(Vec3::ZERO, Vec3::ONE);
    assert_eq!(Vec3::new(0.0, 1.0, 0.0), v);
 }
```

Fails to compile with

```
|| 268 | pub struct Vec3(pub(crate) XYZF32);
||     | ----------------------------------- doesn't satisfy `Vec3: Ord`
||     |
||     = note: the method `clamp` exists but the following trait bounds were not satisfied:
||             `Vec3: Ord`
||             which is required by `&Vec3: Ord`
||             `Vec3: Ord`
||             which is required by `&mut Vec3: Ord`
||             `XYZ<f32>: Ord`
||             which is required by `&XYZ<f32>: Ord`
||             `XYZ<f32>: Ord`
||             which is required by `&mut XYZ<f32>: Ord`
|| For more information about this error, try `rustc --explain E0599`.
```

Have you encountered other issues with having PartialOrd available? I am still open to removing it since I doubt it's very useful.

**Comment by emilk** [comment]
No, I just realized the same thing. I was confused! `PartialOrd` can stay as I don't see it causing any real problems, and the existing `.min` and `.max` does what they should do. Adding `.clamp()` would be nice, but should be a separate issue

**Comment by bitshifter** [comment]
@emilk the one question you didn't respond to was about `to_array()`. There are `From` implementations for vectors, however matrix types have explicit methods for converting to arrays to avoid ambiguities about where the arrays are row or column major. This is a little inconsistent with the other types, so I can see how someone might go looking for `to_array` on vectors since there are methods like that on matrices. Were you aware of the `From` implementations? Is it work adding explicit methods to match what matrix types do?

**Comment by emilk** [comment]
No, I had missed the From implementations. I do like the explicitness and terseness of .to_array(), and as you say it has better discoverability (though arguably that is more of a rustdoc UI problem than a glam problem).
 
In short, I think adding .to_array() would have some benefit and very little downside, but I don’t feel very strongly about it.

**Comment by bitshifter** [comment]
Just found a reason to add `to_array`, I only have `From<Vec3>` but not `From<&Vec3>`. Could add `From<&Vec3>` I guess, kind of annoying though.
