### ISSUE TITLE
Make `dup_x` etc. methods public

### ISSUE THREAD

**Issue by bitshifter** [bitshifter/glam-rs#14]
These are currently `pub(crate)` but they look like they'd be useful externally based on https://github.com/cessen/psychopath/commit/88e7365bc45b737b4fb0d01943271e51dceca26a#diff-7e162a40d8f4de03dc9ab929005466cfR65

**Comment by cessen** [comment]
Do you mind if I go ahead and expose these now, so I can start using them in Psychopath?

**Comment by bitshifter** [comment]
Sure, go for it.

**Comment by cessen** [comment]
Looking at `Vec3` and `Vec2`, I'm not actually sure what semantics we want there.

For example, in my use-case, even if I were using `Vec3` I would still want the `dup_*` methods to return a `Vec4`, since I'm using it to arrange data for full SIMD utilization.  But I don't know if that's what the semantics should actually be more generally.  Right now the `Vec3::dup_*` returns another `Vec3`.

Do you have any thoughts on that?

**Comment by bitshifter** [comment]
That is a good point. It's not really an easy thing to handle nicely at the moment.

The cases I have internally I've kept it in the same type as that's what my usage has been (e.g. `Vec3::dup_x() -> Vec3`).

Long term, what I was thinking with a swizzle macro would solve that, for example `vec3_swizzle!(v, 0, 0, 0, 0)` would produce a `Vec4` based on the number of lane parameters. That was the idea anyway, I'm hoping it's feasible.

You could use the existing `Vec4::dup_x` if you could cast your `Vec3` to a `Vec4` without going through a redundant `extend` call, but that wouldn't be a very safe API.

It could be solved by adding `Vec3::dup_x_vec4` or something but I think I'd rather not do that as it would lead to an explosion of methods.

Perhaps I should leave these as is for now.

If you want to use intrinsics directly you can convert `Vec3` and `Vec4` to and from `__m128`.

**Comment by cessen** [comment]
Yeah, that all makes sense.

I think maybe what we should do for now, then, is just expose the `Vec4::dup_*` methods since we have a clear concrete use-case for them, and leave the other ones private for now.  When we have a better idea of what they might be useful for, we can expose them with the right semantics then.  Does that sound reasonable to you?

**Comment by bitshifter** [comment]
Yeah, it probably makes sense.

**Comment by cessen** [comment]
The more I'm thinking about this, the more I actually kind of don't want to expose this.  It seems so special-cased, and I think waiting for a shuffle macro would make more sense.  My code in Psychopath still works just fine, even if it isn't maximally efficient, and I can change it once we have shuffling.

**Comment by bitshifter** [comment]
Alright, I'll leave this open in case anyone else appears who has a need for it.
