### ISSUE TITLE
Vec2 + Vec2?

### ISSUE THREAD

**Issue by adsick** [bitshifter/glam-rs#166]
hello, so I tried to learn some Bevy basics and got in troble with some basic Vec2 operations, pls check  [this discussion](https://github.com/bevyengine/bevy/discussions/1938) to know what the problem is.

I expected that everything is more straightforward than ever, we have a Vec2 and another Vec2, we want to add them... but it just pissed me off, I tried to dig into the source code of glam, but found only nothing-explandatory macro-spells(

**Comment by adsick** [comment]
I did extra dereferences which led to XY\<f32\>...

**Comment by bitshifter** [comment]
Some Crush types use SSE2 for storage which is opaque and does not provide direct access to the x, y, etc. components. In the past glam only had accessor functions to set and get component values like `.x()` or `.set_x(x)`. People found these accessors a bit painful to deal with so they were replaced by use of the `Deref` trait which returns a normal struct where x, y, etc. can be accessed directly. This is mostly invisible to users unless you deref the glam type it seems.

The macros are unfortunate but the alternative is copy and pasting the `Vec2` implementation for every different type, e.g. `DVec2`, `IVec2` and `UVec2`. I might actually do that at some point when the interface is stable because the macros make the library internals hard for others to understand. But for now, every time someone wants to add a method to a vector type they would need to do it in 4 or 5 places.
