### ISSUE TITLE
Allow const function calls of various methods

### ISSUE THREAD

**Issue by alice-i-cecile** [bitshifter/glam-rs#173]
This is very useful for specifying configuration. For example, in Bevy I'm trying to write:

```rust
    pub const PADDLE_STARTING_LOCATION: Transform = Transform::from_xyz(0.0, -215.0, 0.0);
    pub const PADDLE_SIZE: Vec2 = Vec2::new(120.0, 30.0);
```
but neither of these are const fn's :(

**Comment by bitshifter** [comment]
Closing as duplicate of #76. There's discussion in there as to why this is the case and what needs to happen to resolve it.

**Comment by bitshifter** [comment]
You can make a const `Vec2` using `glam::const_vec2!`. `Transform` is a bevy type so that's a bit trickier. In contains a `Quat`, `Quat::new` cannot be made `const fn` because it uses SSE `__m128` for storage and there is no `const fn` to initialise one of those. That is the problem, this needs to be addressed in Rust's `std::arch`. Bevy could create a `const_transform!` macro using the `glam` ones in the interim.
