### ISSUE TITLE
Replacing x86/x86_64 specific SIMD vectors with core_simd library

### ISSUE THREAD

**Issue by billyb2** [bitshifter/glam-rs#219]
So while looking through the library, I noticed the library only has SIMD vector support for the x86/x86_64 architectures. While this is honestly great for 99% of users, having to rely on scalar math for architectures like ARM and wasm32, architectures where performance is typically more of an issue, is honestly dissapointing. I've recently been testing using SIMD, and found it difficult to use, until I found the official [core_simd](https://github.com/rust-lang/stdsimd/) crate. I think that allowing using core_simd as a feature flag would be very useful, since the work of supporting multiple architectures is already being done by the core_simd team, and it would allow for SIMD vectors on many many more architectures, with little to no work needing to be done on your side.

**Comment by bitshifter** [comment]
Long term this would probably be a good idea. Originally I had planned to use [packed_simd](https://github.com/rust-lang/packed_simd), but I think that is now abandoned and core_simd is the intended replacement.

I think it's early days yet for this crate so I would prefer wait until it's matured and perhaps getting closer to a stable release before looking at using it.

**Comment by billyb2** [comment]
Alright, that's totally understandable. Would the work to be done for core_simd be done in a seperate branch at first (so then I could start to use it).

**Comment by bitshifter** [comment]
Usually I would develop features like this in a branch and merge them to main when they're ready. Since this would be on a feature toggle there's not really a problem with it being in main.

As I said I probably wouldn't to any work on this until core_simd was "beta" - that is considered ready for people to start using. I primarily focus my efforts on stable Rust with my limited dev time. My observation of depending on nightly crates is that they can break, leaving you with builds that only work on specific nightly versions. This has happened with nalgrabra which is using packed_simd for SoA support. core_simd is at least actively developed so hopefully that wouldn't be so much of a concern there, but until it's further along it's always a risk.

What is your use case for needing this? Is there a particular architecture you are wanting to dev on that you are after SIMD for?

**Comment by billyb2** [comment]
I've currently been looking for ways of increasing the Bevy game engine's performance on WASM, and though that improving the performance of this crate would be a major way to do so.

**Comment by bitshifter** [comment]
For sure. I have plans to added support for WASM intrinsics in #193 . This is reasonably high priority for me especially since they were just stabilised, although I'm a bit busy for the next month so might not happen for a while yet.

The main blocker for WASM support is coming up with a way to run glam's tests on WASM, since regular `#[test]` attributes aren't supported. Also being able to benchmark WASM would be nice as well. If you find any nice solutions to these with your bevy work let me know.

**Comment by joseluis** [comment]
> The main blocker for WASM support is coming up with a way to run glam's tests on WASM, since regular `#[test]` attributes aren't supported. Also being able to benchmark WASM would be nice as well.

maybe this crate could be used for testing?:
https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/index.html

this other crate does some wasm benchmarks that may serve as inspiration:
https://github.com/alexcrichton/rust-wasm-benchmark

**Comment by bitshifter** [comment]
@billyb2 I have implemented a wasm32 simd128 version of glam. It currently passes all of glams tests. I haven't tried using it for any real application yet and I don't have any way to benchmark it right now so don't know how it compares to the non simd128 version. If you were interested in trying it out in bevy it's all on this branch https://github.com/bitshifter/glam-rs/tree/wasm32-simd. 

To run the tests (on Linux) you can do:

```
RUSTFLAGS="-C target-feature=+simd128" wasm-pack test --headless --firefox --chrome
```

**Comment by billyb2** [comment]
I'll test it later this afternoon, thank you so much for your work!

**Comment by billyb2** [comment]
I tried very quickly replacing the old glam with the new glam in Bevy, and it worked perfectly. Unless the SIMD stuff makes it into a new release, however, it probably won't make it into Bevy without patching.

**Comment by bitshifter** [comment]
I have a few more smaller things to do but it should make it into a new release soon.

**Comment by bitshifter** [comment]
@billyb2 were you able to tell if there was any performance difference with the simd128 stuff enabled?

**Comment by billyb2** [comment]
Yea, I think I definetly noticed a speed improvement in my game that heavily uses glam math on WASM.

**Comment by bitshifter** [comment]
No, when core_simd is stable I will look at using it so let's leave this
open for now.

**Comment by bitshifter** [comment]
std::simd has made it to nightly, I might give it a try. It's probably not too different to wasm API wise, shouldn't be too hard to get something working, see if any features are missing and how performance compares https://doc.rust-lang.org/nightly/std/simd/index.html

**Comment by bitshifter** [comment]
There is a working `std::simd` implementation in the std-simd branch, it can be build on `nightly` using the `std-simd` feature.

https://github.com/bitshifter/glam-rs/tree/std-simd

**Comment by aloucks** [comment]
@bitshifter I noticed that the code to check for a positive dot product in `Quat::slerp` was missing/removed from the std-simd branch. This will likely result in the slurp path changing when the dot product is negative. I suspect the unit test(s) are not sufficient if they are still passing. 

If this is intended, the note here should be added back to the public documentation:

https://github.com/bitshifter/glam-rs/blob/019614fbbcaf9bb397be50856d0062639b63b0fb/src/core/sse2/quaternion.rs#L52-L57

**Comment by bitshifter** [comment]
It's not intended, this code was copied from one of the other implementations before that fix was made. It does seem that the unit test isn't catching it though.

**Comment by bitshifter** [comment]
After 0.21 I made a new branch for the core::simd work. I am a bit undecided about merging this back into main yet. https://github.com/bitshifter/glam-rs/tree/coresimd

**Comment by billyb2** [comment]
>  I am a bit undecided about merging this back into main yet.

How come?
