### ISSUE TITLE
SizeVec?

### ISSUE THREAD

**Issue by sarkahn** [bitshifter/glam-rs#232]
I was wondering if there's any chance we could get a "SizeVec" or "USizeVec" (Vec whose elements are usize). I use (usize,usize) a lot to represent 2D size, I find myself wanting to replace them with UVec2 to make the math easier to read, but then I have to convert to usize to interact with array indices and such.

**Comment by bitshifter** [comment]
Hey there. I am a bit reluctant to add this one. Since glam is not a generic library there's a bit more overhead to adding and maintaining new types. I will sit on this and see if there is further demand for it though.

If there is anything you can think of that would make it easier to work with usize with existing types let me know.

**Comment by sarkahn** [comment]
That makes sense, thanks for the consideration! I think even implementing `From<(usize,usize)>` for UVec2 and UVec2 would make things a lot smoother for how I'm using them, if that would be possible.
