### ISSUE TITLE
Expose Quat::from_rotation_axes

### ISSUE THREAD

**Issue by kvark** [bitshifter/glam-rs#235]
I was looking for a way to get a `Quat` of the inverse of `look_at_rh`. Apparently, it comes down to the following code:
```rust
        let f = dir.normalize();
        let s = glam::Vec3::from(up).cross(f).normalize();
        let u = f.cross(s);
        glam::Quat::from_rotation_axes(s, u, f)
```
`from_rotation_axes` is used internally, but unfortunately not exposed. Is there a good reason for it?

**Comment by bitshifter** [comment]
It's a common method internally which is used by different types like `Mat3`, `Mat3A`,`Mat4` and `Affine3D`. The easiest way to do this would be to go via `Mat3` since the axes are just a 3x3 matrix column vectors so:

```
let f = dir.normalize();
let s = glam::Vec3::from(up).cross(f).normalize();
let u = f.cross(s);
glam::Quat::from_mat3(Mat3::from_cols(s, u, f))
```

That said if via `Mat3` is inconvenient I could expose it, probably as `from_cols` or something to stick with the column vector naming.

**Comment by kvark** [comment]
Good point, I should just use `Mat3` intermediate.
