### ISSUE TITLE
Primitive integer ops for UVec and IVec

### ISSUE THREAD

**Issue by bonsairobo** [bitshifter/glam-rs#236]
I'm thinking about replacing my own vector types with glam, but there is some missing functionality I need first:

- Not
- BitAnd
- BitOr
- BitXor
- Shl
- Shr
- ~~Rem~~

Would a PR to add these `impl`s to `UVec` and `IVec` be welcome?

**Comment by bitshifter** [comment]
Yep sure thing. I thought I added Rem already, maybe that was just on float types.

**Comment by bonsairobo** [comment]
Ah yes. You `UVec` and `IVec` have `Rem` already.

**Comment by bonsairobo** [comment]
I think I might need some guidance here.

My first take, based on reading the code, is that I should:

1. Add a `PrimInt` trait to bundle all of the scalar ops
2. Add an `IntegerVector` trait that bundles the vectorized ops
3. `impl IntegerVector` for `XY`, `XYZ`, and `XYZW`
4. `impl` the vectorized ops for `UVec` and `IVec` using a macro

Does that seem right, @bitshifter ?

**Comment by bitshifter** [comment]
Ah yes, I have been meaning to document how things work internally for a while, but still haven't got around to it.

The way glam works is there are inner types, e.g. `XYZ` or SSE `__m128` and there are various traits that are implemented for those types. The public API is generally defined using macros and the implementation will be expressed using these inner types and trait implementations. Because the types you are looking at don't currently have a SIMD implementation you only need to worry about `XY`, `XYZ` and `XYZW`.

What you are proposing sounds about right. Perhaps `BitVector` as a trait name, `IntegerVector` sounds too broad to me. You may notice in code that I have  `Vector2`, `Vector3` and `Vector4` traits and so on. This is because these will all be implemented for SIMD types and for many ops you need to know how many elements you are dealing with. However I am not currently using SIMD for any of the `IVec*` or `UVec*` types so you can get away with a single trait. I think that's fine for now.

**Comment by bonsairobo** [comment]
@bitshifter Any plans to support SIMD for `UVec` and `IVec`? I would be interested in that functionality.

**Comment by bitshifter** [comment]
@bonsairobo I didn't have any plans to add SIMD support for these. SSE2 for one only supports signed integers in any case.

Also adding SIMD raises many questions like should there be an `IVec3A` type like there is for `f32`. It's a bit of a nuisance having two vector 3 types for `f32`.

I'd rather not do it for other primitive types unless there is a large benefit and strong demand from users.

**Comment by bonsairobo** [comment]
I would definitely use an `IVec3A`. And I'm happy to attempt a PR for that at some point if you're not opposed.

**Comment by bitshifter** [comment]
There are a few things it would need to happen as part of a PR for this:

* Do other popular ISAs support i32x4 (AFAICT yes they do, sse2, wasm32, arm, aarch64 all support i32x4 simd)
* Is it actually faster - i.e. add benchmarks
* Does the shift behaviour of i32x4 SIMD for sse2 and wasm32 match that of native Rust i32 in release? I try to ensure glam behaves the same with and without SIMD

The most likely candidates for i32x4 SIMD would be IVec4 and IVec3A. I generally found using SIMD instructions for Vec2 didn't provide a performance benefit in the f32 case so I imagine the same would be true for i32.

One other thing to consider is using SIMD for IVec* and Vec* will mean more contention for the same registers. Using scalar code for integer ops and the vector units for float ops might still give better performance. Ultimately it comes down to what the workload is and profiling it to confirm performance. Some of my colleagues worked on LA Noire and on that game they shifted some math ops to integer units to get better CPU throughput (I don't recall which architecture they did that on, maybe PS3/PPU). The tl;dr being, I wouldn't assume that shifting integer math to vector units will necessarily translate into improved performance.

**Comment by bonsairobo** [comment]
For now I think we can close the issue, but thanks for the guidance and quick turnaround on the PR! Before attempting any kinds of integer SIMD, I will probably do a quick and dirty benchmark to see what's on the table. Thanks again.

**Comment by bitshifter** [comment]
Sounds good. Feel free to hit me up if you need any help with getting some SIMD going in glam.
