### ISSUE TITLE
Adding CUDA native alignment feature

### ISSUE THREAD

**Issue by anderslanglands** [bitshifter/glam-rs#254]
I have a fork here https://github.com/anderslanglands/glam-rs/tree/cuda that adds a new feature, "cuda", that when enabled adds the appropriate repr(align(X)) attributes to match CUDA's built-in float2, float3, float4 types, as specified here: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#built-in-vector-types

I'd like to submit a PR for this that would enable us to use glam on the GPU with these alignments.

**Comment by bitshifter** [comment]
Yeah that looks fine in principle. I'd prefer it if you use `cfg_attr` to change attributes rather than duplicating type declarations, it would be easier maintenance wise.

https://github.com/bitshifter/glam-rs/discussions might be a better forum for these questions rather than issues (hardly anyone uses discussions, I think it's not a well known feature of GitHub) or you can open a draft PR.

**Comment by bitshifter** [comment]
Also, you'll need to update tests

**Comment by anderslanglands** [comment]
Yeah I was just about to open a PR but your contributing guidelines said to open an issue first. Will look at the discussions in the future. I''ll open a PR now.

What tests needs updating? I've already added feature="cuda"-gated tests for size and alignment, and the types should be otherwise be tested automatically since it's just an attribute change?

**Comment by bitshifter** [comment]
The tests you've added are static asserts that get checked at compile time. There are old alignment tests in tests/*.rs that will need to be updated as well.

**Comment by anderslanglands** [comment]
Gotcha. Will do.
