### ISSUE TITLE
Bytemuck cast fails for quat / vec4

### ISSUE THREAD

**Issue by IcanDivideBy0** [bitshifter/glam-rs#266]
Hello, I'm having really strange behaviors with bytemuck & glam.

Consider the following:
```rust
fn main() {
    dbg!(bytemuck::cast_slice::<glam::Quat, u8>(&[glam::Quat::IDENTITY]));
    dbg!(bytemuck::cast_slice::<u8, glam::Quat>(&[0u8; 16]));
}
```
Works fine, but this one will panic
```rust
fn main() {
    dbg!(bytemuck::cast_slice::<u8, glam::Quat>(&[0u8; 16]));
}
```
```
thread 'main' panicked at 'cast_slice>TargetAlignmentGreaterAndInputNotAligned', /home/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.7.3/src/lib.rs:119:3
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: bytemuck::something_went_wrong
             at /home/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.7.3/src/lib.rs:119:3
   3: bytemuck::cast_slice
             at /home/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.7.3/src/lib.rs:319:15
   4: glam_bytemuck_fail::main
             at ./src/main.rs:6:10
   5: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This is really strange, why having a first unrelated cast change the behavior of the second one ?

rustc 1.57.0 (f1edd0429 2021-11-29)
simple reproduction: https://github.com/IcanDivideBy0/glam_bytemuck_fail

**Comment by IcanDivideBy0** [comment]
It looks like it's more a bytemuck issue than a glam one, so i'm closing this one

**Comment by bitshifter** [comment]
Yes, it will be because u8 is 1 btye aligned and Quat/Vec4 is 16 byte aligned. So it is undefined behaviour to cast the u8 slice to Quat/Vec4 if the alignment is not correct. This is something that bytemuck cannot know at compile time. It would be possible to allocate a Vec of u8 with the correct alignment and it would then be ok to cast but that would need to be a runtime check.

You can read from a slice without casting with  https://docs.rs/glam/0.20.2/glam/f32/struct.Quat.html#method.from_slice
