### ISSUE TITLE
write docs

### ISSUE THREAD

**Issue by bitshifter** [bitshifter/glam-rs#3]
Need to add crate and module level docs plus docs describing methods and requirements of parameters.

- [x] `Mat2`
- [x] `Mat3`
- [x] `Mat4`
- [x] `Quat`
- [x] `Vec2`
- [x] `Vec2Mask`
- [x] `Vec3`
- [x] `Vec3Mask`
- [x] `Vec4`
- [x] `Vec4Mask`

**Comment by cessen** [comment]
If you're looking for contributors, I would love to take on documenting the methods on `Vec4` and `Vec4Mask` to get started.  As an example of the quality of documentation I typically write, 

As a bit of background, I'm currently maintaining my own equivalent to glam as a sub-crate in one of my projects, because at the time I started it glam didn't exist.  I just recently found glam, and it's basically the same as my sub-crate, except better!  So I'm planning to switch over to glam, and would love to contribute however I can.

**Comment by bitshifter** [comment]
Hi @cessen, I'd happily accept some documentation PRs if you are interested! The ropey docs look great, super thorough and readable. I don't really have any requirements or guidelines around method docs, I mostly wanted to ensure to document preconditions, e.g. if an input should be normalised or in a certain range to get valid output, and if there are any panics. I made a small start on the quaternion docs they have some examples of what I was trying to cover. 

One thing to note with the vector types is the implementation is split between 3 files, common, f32 and sse2. The common and sse2 files are the ones that will be used for doc generation I think.

**Comment by cessen** [comment]
Great!  I'll get started on that within the next couple of weeks or so.
