### ISSUE TITLE
Add `Mat4::ortho`

### ISSUE THREAD

**Issue by icefoxen** [bitshifter/glam-rs#32]
Because orthographic projections are cool.  If you want this, I'll happily PR it.

**Comment by bitshifter** [comment]
Hi, yeah I'd happily accept a PR for orthographic projections! I'd suggest following the current naming convention that's used for perspective projections like `Mat4::perspective_infinite_rh` and `Mat4::perspective_infinite_reverse_rh`. Note that there's only right handed perspective creation functions because that's what people have contributed. Up to you if you provide right or left handed or both. Current perspective creation functions are in the 0 to to 1 depth range.

So perhaps `Mat4::orthographic_rh` or whatever. If it makes sense for it to be "infinite" like the others include that I guess (see https://github.com/bitshifter/glam-rs/pull/23). I'm no expert on projection matrices though, whatever makes sense to you.

Also I've tried to add tests for most functionality in `glam`, but coming up with tests for projection matrices is a bit annoying so definitely not a requirement for a PR.

**Comment by bitshifter** [comment]
Not to self, I found some projection matrix unit tests in handmade math that I might give me some ideas for glam https://github.com/HandmadeMath/Handmade-Math/blob/master/test/categories/Projection.h
