### ISSUE TITLE
Quat implements from_array([f32; 4]), but not From<[f32; 4]>

### ISSUE THREAD

**Issue by cybersoulK** [bitshifter/glam-rs#320]
```
let behind_rotation = glam::Quat::from_array(behind.rotation);
let ahead_rotation = glam::Quat::from_array(ahead.rotation);

rotation: glam::Quat::slerp(behind_rotation, ahead_rotation, lerp_percentage).into(),
```

being able to do this, is much cleaner than previous

```
rotation: glam::Quat::slerp(behind.rotation.into(), ahead.rotation.into(), lerp_percentage).into(),
```

**Comment by bitshifter** [comment]
This is intentional. `Quat` requires normalised data. With `impl From` it is too easy for users to pass through invalid data without realising, especially in generic code. Instead `from_array` is provide because it's more explicit and the constraints of the method are clearly documented. While it is possible to document `impl From` for `Quat` documentation of trait implementations is fairly hidden in Rust docs, you have to go looking for it.
