### ISSUE TITLE
Bug: Affine3A * f32 scales translation part

### ISSUE THREAD

**Issue by rasmusgo** [bitshifter/glam-rs#351]
The translation of a transformation should not be scaled when multiplying with a scalar on the right. But it currently is, see

https://github.com/bitshifter/glam-rs/blob/34c57c63a454417a3ce9a1b3c1ac7b6518fdaabe/src/f32/affine3a.rs#L520

This leads to incorrect behavior when trying to use scalars for scaling.

**Comment by rasmusgo** [comment]
Some more details might be helpful. I ran into this issue when I was composing affine transformations and a uniform scaling. I had an expression similar to u = A•s•B•v where A and B are affine transformations, s is a scalar, and u and v are vectors treated as points. My expectation was that the scalar s would act just like an affine transformation with only uniform scaling. That is not what happened though. It instead acted like s•A•B•v which is different because of the translation involved in the transformation. This looks like a bug to me. Transformations are not commutative but they should be associative.

**Comment by bitshifter** [comment]
Thanks for the report. The intent with `Affine3A` is to largely be interchangeable with a `Mat4` that contains an affine transform. In the `Mat4` case multiplying an affine transform by a scalar value would scale the homogeneous coordinate, so it probably doesn't make sense to to that to a `Mat4` affine transform. Given that, I think I'd be inclined to remove this method from the `Affine*` types. Possibly I could replace it with something more explicit like a `scale` method that only applies to the matrix3 member. Otherwise I think there's a bit of ambiguity between the `Affine3A` and `Mat4` interface.

**Comment by bitshifter** [comment]
I've removed the mul by scalar methods from affine types. I'm a bit on the fence about adding a scale method, you can create a new scale affine with `from_scale` and multiply by that, it does do a bit of unnecessary work with the zero translation though. It's also possible to scale the affine types matrix directly. So there are a couple of options there.

Mostly I wanted to remove these before bumping 0.21 to 0.22. Removing functionality is a breaking change, adding methods is not :)
