### ISSUE TITLE
Implement Index / IndexMut for BVec4 et al.

### ISSUE THREAD

**Issue by wusticality** [bitshifter/glam-rs#373]
Currently, the `Index` and `IndexMut` traits are implemented for `Vec4`, but not for `BVec4`. I'd like to request these traits be implemented so that there's better parity between `BVec4` and `Vec4`. It's possible this should be done for other types as well.

**Comment by bitshifter** [comment]
Did you have a use case for these index traits? 

`IndexMut` in particular is problematic because for in the SIMD case the underlying type is effectively `[i32; 4]` and the only really valid values are `0` or `-1`. If other values are used then a lot of functionality will give unexpected results.

I endeavour to keep the interface the same between SIMD and scalar implementations, so for this reason I don't think that `IndexMut` is something I would add.

I could add `Index` support if it's something that people would have a use for.

**Comment by wusticality** [comment]
Just saw this, looking through my code, looks like I did this:

```rust
/// Adds index-based accessor functions to BVec4.
pub trait BVec4Ext {
    fn get(&self, index: usize) -> bool;
    fn set(&mut self, index: usize, value: bool);
}

impl BVec4Ext for BVec4 {
    fn get(&self, index: usize) -> bool {
        match index {
            0 => self.x,
            1 => self.y,
            2 => self.z,
            3 => self.w,
            _ => panic!("index out of bounds")
        }
    }

    fn set(&mut self, index: usize, value: bool) {
        let field = match index {
            0 => &mut self.x,
            1 => &mut self.y,
            2 => &mut self.z,
            3 => &mut self.w,
            _ => panic!("index out of bounds")
        };

        *field = value;
    }
}
```
