### ISSUE TITLE
Incorrect docs on `any_orthonormal_vector`

### ISSUE THREAD

**Issue by devil-ira** [bitshifter/glam-rs#380]
[The docs](https://docs.rs/glam/latest/glam/f32/struct.Vec3.html#method.any_orthonormal_vector) mention "The input vector must be finite and non-zero.", but it seems that it should be "The input vector must normalized".
The [Panics](https://docs.rs/glam/latest/glam/f32/struct.Vec3.html#panics-8) section of the docs does mention the correct requirement.

Note that the incorrect docs are in three places: `Vec3`, `Vec3A` and `DVec3`.

**Comment by bitshifter** [comment]
I'm not sure at this stage if the panic is overly conservative. Did you encounter an issue with non normalized input?

**Comment by bitshifter** [comment]
Looking at the mention and the related bevy bugs it seems like possible the input was bad already, like normalize had been called on a zero length vector which would result in NaNs?

Looking at the implementation of `any_orthonormal_vector` it's not totally clear that the input needs to be normalized, I may have slapped those glam asserts around a bit haphazardly in this case.

**Comment by Ph4ntomas** [comment]
It is necessary for the input to be normalized.

The papers (both pixar's and the ones before) specifically work on unit vectors, because the math breaks otherwise :)

Applying the formula to this non-unit vector `(1, 2, 3)` leads to the following "orthonormal" vector: `(-0.5, 0, -2)`
The dot product of these two is `-6.5`, so they are not even near orthogonal as the dot product of orthogonal vector is always 0

**Comment by bitshifter** [comment]
Cool, thanks for looking into it @Ph4ntomas
