### ISSUE TITLE
`Vec4` uses `BVec4` for scalar implementations and `BVec4A` for SSE implementations

### ISSUE THREAD

**Issue by Radbuglet** [bitshifter/glam-rs#407]
...this is in contrast to `Vec3A`, which uses `BVec3A` for both its scalar and SSE implementations.

The easiest change is likely to change the scalar `Vec4` method signatures to use `BVec4A` vectors to maintain consistency.

**Comment by bitshifter** [comment]
This is intentional. The `BVec4` type uses bool internally and `BVec4A` uses SIMD internally, `BVec4` is faster if you are working with scalar types and `BVec4A` is faster if you are using SIMD.

People should not be mixing `scalar-math` and non `scalar-math` features so I don't think this type difference should cause any issues generally. The interface of `BVec4` and `BVec4A` should be largely identical and interchangeable.
