### ISSUE TITLE
transpose() for Affine transforms?

### ISSUE THREAD

**Issue by Firestar99** [bitshifter/glam-rs#424]
`Affine2` and `Affine3A` have an `inverse()` method which inverses the matrix and efficiently inverses the translation vector as well:
https://github.com/bitshifter/glam-rs/blob/f8eacbc09a60fff4f7643eb15d649f9a45ecbfc1/src/f32/affine3a.rs#L419-L428

But inverting a matrix is still quite expensive, especially on a GPU (I'm using rust-gpu). If however the affine transformation does not scale the matrix, one could instead of inverting just transpose the matrix and do the same efficient translation vector inverse, but no such method exists for Affine transformations. Is there a particular reason for them missing or have they just been forgotten and I may PR them?

**Comment by bitshifter** [comment]
While affine transforms mimic a homogeneous 4x4 (or 3x3 for 2D) matrix, they are effectively 3x4 matrices with an implicit (0,0,0,1) row which is used for operations like multiplication and inverse. Because they don't actually have a 4th row, a transpose would effectively discard the 4th column (the translation). Therefore I don't think it really makes sense to provide a transpose method. Possibly to do what you want you could just transpose the matrix3 part of the affine transform?

**Comment by Firestar99** [comment]
> Possibly to do what you want you could just transpose the matrix3 part of the affine transform?
That's exactly what I would like to have. Though I do agree just naming the function `transpose()` may be confusing... though can't think of a better name right now.
