### ISSUE TITLE
Threshold for `is_normalized` seems wrong

### ISSUE THREAD

**Issue by Jondolf** [bitshifter/glam-rs#480]
The `is_normalized` method for vectors looks like this:

```rust
    /// Returns whether `self` is length `1.0` or not.
    ///
    /// Uses a precision threshold of `1e-4`.
    #[inline]
    #[must_use]
    pub fn is_normalized(self) -> bool {
        // TODO: do something with epsilon
        math::abs(self.length_squared() - 1.0) <= 1e-4
    }
```

The threshold in the docs appears to be slightly different from the actual threshold used, if my calculations are correct.

If we have a vector with a length of `1.0 + 1e-4` (at the exact threshold mentioned in the doc comment), the squared length is roughly `1.0 + 2e-4`:

$$
\begin{align}
L &= 1 + 10^{-4} \\
L^2 &= 1.00020001 \approx 1 + 2 \cdot 10^{-4}
\end{align}
$$

This means that the threshold for the squared length should actually be `2e-4` based on the documentation comment.

**Comment by bitshifter** [comment]
The comment describes the epsilon value used,  I don't think that changing it to 2e-4 would add any clarity.

**Comment by Jondolf** [comment]
The doc comment is talking about the length, so I find it confusing that the mentioned threshold would be for the squared length instead. The fact that it internally uses `length_squared` seems like an implementation detail to me. Based on the documentation, I would expect a vector with length `1.0 + 1e-4` to still be valid (or slightly less in case there are numerical accuracy issues), but with this implementation, I don't think it would be.

This isn't a big deal by any means, and the difference is small of course, but I just found the comment misleading.

**Comment by bitshifter** [comment]
OK, I thought you were suggesting changing the documentation, not the code. It is somewhat arbitrary what epsilon is used. `2e-4` would also not be sufficient for a vector of length 1 +/- 1e-4 to be considered normalized due to floating point precision, a value of `0.00020003319` would make that length considered normalized Of course it would also be true for slightly larger values than 1e-4 due to float precision (up to 1 +/- 0.0001000761). values will be different for f64.

Sure though, I can change the epsilon.

The reason length_squared is used is to avoid a square root.
