### ISSUE TITLE
Add `fast_normalize` to `Quat` (and maybe other types)

### ISSUE THREAD

**Issue by janhohenheim** [bitshifter/glam-rs#540]
See this issue: https://github.com/bevyengine/bevy/issues/14302 and the accompanying PR: https://github.com/bevyengine/bevy/pull/14316#discussion_r1679823439 for context and an example implementation.

The motivating problem is this: operating multiple times on a normalized quaternion will accumulate small errors that will eventually result in it no longer being normalized. While the error is still small, a full `.normalize()` is not necessary; there are cheaper ways to get such a quaternion normalized again.

**Comment by bitshifter** [comment]
What is the performance difference compared to `normalize`? Do you have an estimate of relative error compared to `normalize`?

**Comment by janhohenheim** [comment]
Pinging @IQuick143 for that

**Comment by BD103** [comment]
> What is the performance difference compared to `normalize`? Do you have an estimate of relative error compared to `normalize`?

I created some benchmarks: `fast_normalize()` (blue) appears to only be marginally faster that `normalize()` (red), though more consistent in speed (due to its height). Of course, this is in the terms of picoseconds, so...

<img width="965" alt="image" src="https://github.com/user-attachments/assets/2704babf-34b2-4d96-b3b9-d5677574be09">

You can find the benchmarks and commands to generate the report [here](https://gist.github.com/BD103/9e5da0322dd0379a4c81f752e7eec384). I ran the benchmarks on an M1 MacBook Air, but it would be good to test with different CPUs and instruction support.

**Comment by BD103** [comment]
To add on to this, I generated the assembly (in ARM) using `cargo rustc --release -- --emit asm`. The only difference that `fast_normalize()` introduces is an extra `fmov` and `fsub` (copy and subtract) instruction, which replaces `normalize()`'s `fsqrt` instruction.

In summary, I believe that `fast_normalize()` is only worthwhile when there is no square root hardware support, since else it introduces 1 extra instruction. Per-platform testing is still warranted, but I don't think this should replace `normalize()` for all platforms.

```s
_normalize:
	.cfi_startproc
	fmul	s2, s0, s0
	fmul	s3, s1, s1
	fadd	s2, s2, s3
	fsqrt	s2, s2
	fmov	s3, #1.00000000
	fdiv	s2, s3, s2
	fmul	s0, s2, s0
	fmul	s1, s2, s1
	ret
	.cfi_endproc

	.globl	_fast_normalize
	.p2align	2
_fast_normalize:
	.cfi_startproc
	fmul	s2, s0, s0
	fmul	s3, s1, s1
	fadd	s2, s2, s3
	fmov	s3, #3.00000000
	fsub	s2, s3, s2
	fmov	s3, #0.50000000
	fmul	s2, s2, s3
	fmul	s0, s2, s0
	fmul	s1, s2, s1
	ret
	.cfi_endproc

	.p2align	2
```

<details>
  <summary>View code that generated this assembly</summary>

```rust
use glam::Vec2;

#[no_mangle]
pub fn normalize(v: Vec2) -> Vec2 {
    v.normalize()
}

#[no_mangle]
pub fn fast_normalize(v: Vec2) -> Vec2 {
    let length_squared = v.length_squared();
    v * (0.5 * (3.0 - length_squared))
}

fn main() {}
```

</details>

**Comment by bitshifter** [comment]
I think for now I don't want to add this to glam. Benefits seem reasonably small, will see how it pans out in bevy.

**Comment by Jondolf** [comment]
It is worth noting that while the difference is ordinarily very small, and in my case `normalize` even seems to be slightly faster (probably noise):

![kuva](https://github.com/user-attachments/assets/d6bbcc5e-b7f5-47a6-86f8-8cb710a11d9e)

`fast_normalize` seems to be nearly an order of magnitude faster when `libm` is enabled:

![kuva](https://github.com/user-attachments/assets/fd223acc-75ad-41dd-a09d-00daa8bbceb4)

(using BD103's benchmark)

I personally think it might be worthwile to add it for this reason alone.

**Comment by Jondolf** [comment]
Nalgebra also has [`renormalize_fast`](https://docs.rs/nalgebra/latest/nalgebra/base/struct.Unit.html#method.renormalize_fast) using the same first-order Taylor expansion.
