### ISSUE TITLE
Types shouldn't implement `Display` since a "canonical representation" is not really clear

### ISSUE THREAD

**Issue by clarfonthey** [bitshifter/glam-rs#574]
This was recommended by #28 and I mostly disagree with the approach that everything should implement `Display`. We were discussing this for Bevy since we re-export types from `glam`.

Essentially, it's unclear how you might want to display a vector or matrix, and it's best for people to interpret this as needing to format it themselves. Personally, I think that display implementations like `[x, y]` for vectors should be exposed via the `Debug` implementation, not `Display`.

**Comment by bitshifter** [comment]
To be clear, glam implements both `Debug` and `Display`.

This would be a breaking change and I think it's likely that there would be opinions among glam users for and against doing this. Can you provide more details of the bevy related discussion?

**Comment by bitshifter** [comment]
Because of Rust's orphan rule it is not possible for a glam user to provided their own implementation of `Display` for glam types, if they wanted to do that they would need to create a new type and implement `Display` how they see fit on it. Whether glam types implement `Display` or not does not change that but they exist for convenience for any user who might want to a glam type with `Display` formatting. 

I don't see any reason or advantage in removing it, it doesn't prevent anyone from making a newtype wrapper that implements Display how they like and for people who find it convenient can use glam's implementation.

However I am open to suggestions on changing how things are displayed by glam.
