### ISSUE TITLE
Confusing Debug format of Vec3

### ISSUE THREAD

**Issue by emilk** [bitshifter/glam-rs#61]
The `Debug` formater for `Vec3` includes the dummy fourth component, which I find somewhat confusing: 

Actual: `Vec3(__m128(0.8072419, -7.489461, 14.073505, 13.841213))`

Expected: `Vec3(0.8072419, -7.489461, 14.073505)`

**Comment by bitshifter** [comment]
I'm sort of in two minds about this because the debug format does show all the data in the `__m128` so it can be useful for debugging problems in `Vec3` itself. That said it probably doesn't make much sense to users of the library.

**Comment by kettle11** [comment]
I've also found the formatting a bit confusing.

Often when debugging I'll log a bunch of `Vec3`s at once. More than once I've spent time writing formatting to make `Vec3`s easier to skim quickly in the debug output.

**Comment by bitshifter** [comment]
Note that this will kind of go away when I finish #36 since the default `Vec3` will just be `Vec3(32, f32, f32)` then, but there will still be a SIMD type (currently `Vec3Align16` unless I come up with a better name) so this will still be an issue for the new type. I guess since it's confusing for people I'll change it and maybe add a separate debug print if I need it for debugging SIMD issues.
